; Testsuite works with MAME to run functions/methods on the MD, report results via the debugger,
; and then process the result output using external tool.

; This file may not contain code
	include 'testsuite/util.asm'

; current_test.asm is generated by a test runner and should contain a single
; "include" statement with the path of the current classname (as defined in the junit file)
	include 'testsuite/current_test.asm'

TestsComplete:
	TestsuiteEmulatorExit

TestLoop:
	bra.s TestLoop